name: Random Daily Commits

on:
  schedule:
    - cron: "0 11 * * *" # Executa uma vez ao dia as 11:00 UTC

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write # Permissão para criar PR

jobs:
  random_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "peregrinno"
          git config --global user.email "joseluan74@gmail.com"

      - name: Create new branch
        run: |
          BRANCH_NAME="random-commits-$(date +%Y%m%d_%H%M%S)"
          git checkout -b $BRANCH_NAME
          echo "Criando nova branch $BRANCH_NAME"

      - name: Generate random number of commits
        run: |
          # Gera um número aleatório entre 1 e 10
          RANDOM_COMMITS=$(( ( RANDOM % 10 )  + 1 ))
          echo "Gerando $RANDOM_COMMITS commits para o dia."

          # Loop para gerar os commits
          for i in $(seq 1 $RANDOM_COMMITS); do
            echo "Commit número $i em $(date)" >> commit.txt
            git add commit.txt
            git commit -m "Commit automático $i de $RANDOM_COMMITS no dia $(date)"
          done

      - name: Create Python Hello World file with random prefix
        run: |
          PREFIX=$(shuf -i 10000-99999 -n 1)
          FILENAME="auto_src/${PREFIX}_helloworld.py"
          echo 'print("Hello, World!")' > $FILENAME
          git add $FILENAME
          git commit -m "Adicionando Hello World em Python com prefixo aleatório: $FILENAME"

      - name: Create JavaScript Hello World file with random prefix
        run: |
          PREFIX=$(shuf -i 10000-99999 -n 1)
          FILENAME="auto_src/${PREFIX}_helloworld.js"
          echo 'console.log("Hello, World!");' > $FILENAME
          git add $FILENAME
          git commit -m "Adicionando Hello World em JavaScript com prefixo aleatório: $FILENAME"

      - name: Push commits to new branch
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN3D }}
        run: |
          git push https://x-access-token:${{ secrets.TOKEN3D }}@github.com/peregrinno/auto-commits.git $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Adicionando commits automáticos"
          branch: $BRANCH_NAME
          base: main
          title: "Adicionando commits automáticos via branch $BRANCH_NAME"
          body: "Este pull request contém commits automáticos gerados pelo script."

      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.payload.pull_request.head.ref}`,
            });
            if (pulls.length > 0) {
              const pr = pulls[0];
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'merge',
              });
            }
